name: CD (Deploy to Railway)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Install Node dependencies and build
        run: |
          npm ci
          npm run build

      - name: Generate application key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Install Railway CLI
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
          
          # Deploy
          railway login --ci $RAILWAY_TOKEN
          railway up --detach

      - name: Verify deployment
        run: |
          echo "✅ Deployment completed to Railway"
          echo "Your app is live at: https://${{ secrets.RAILWAY_APP_NAME }}.railway.app"
